In [5]:
import numpy as np

In [16]:
#single dimensional 
n1=np.array([10,20,37,45])
n1

array([10, 20, 37, 45])

In [18]:
#check the type of n1.
type(n1)

numpy.ndarray

In [22]:
#multi dimensional 
n2=np.array([[10,20,30],[60,89,67]])
n2


array([[10, 20, 30],
       [60, 89, 67]])

In [25]:
type(n2)

numpy.ndarray

In [26]:

import numpy as np
n3=np.zeros((2,3)) #this syntax fill the specified dimension of array by zero.
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
n4=np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
#numpy full matrix
n5=np.full((3,3),(5)) ##this syntax fill the specified dimension of array by any number specified by the user.
n5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [29]:
n6=np.full((1,1),(8))
print(n6)

[[8]]


In [30]:
#initialize array within a range

n7=np.arange(20,31,1)  
#np.arange(start,end,increment/decrement). 
# Remember, here 20 is inclusive and 31 is exclusive.
n7

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [31]:
n8=np.arange(50,100,5)
n8

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [4]:
#initializing Numpy array with random numbers
import numpy as np
a1=np.random.randint(10,100,10) #(starting value,final value,no. of element)
a1


array([17, 75, 72, 99, 41, 43, 48, 36, 38, 89])

In [5]:
#checking the shape of NumPy arrays
a2=np.array([[1,2],[3,4],[5,6]])
a2.shape

(3, 2)

In [6]:
# rearranging the a2(initially in 3*2 shape) into 2*3 shape without altering the original data.
a2.shape=(2,3)
a2

array([[1, 2, 3],
       [4, 5, 6]])